=== HOSTbioinformatics/ExchangeFormats/XML-Formats/definitions/locus.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        xmlns:locus="http://bioinformatics.hochschule-stralsund.de/locus"
        targetNamespace="http://bioinformatics.hochschule-stralsund.de/locus"
        elementFormDefault="qualified" >
    <complexType name="nucleosome">
        <sequence>
            <element name="pos" type="unsignedLong" maxOccurs="1"
                     minOccurs="1"/>
            <element name="mpos" type="unsignedLong" maxOccurs="1"
                     minOccurs="1"/>
        </sequence>
    </complexType>
    <complexType name="locus">
        <sequence>
            <element name="nucleosome" type="locus:nucleosome"
                     maxOccurs="unbounded" minOccurs="1"/>
        </sequence>
        <attribute name="chromosome" type="string"/>
        <attribute name="firstbase" type="unsignedLong"/>
        <attribute name="lastbase" type="unsignedLong"/>
        <attribute name="experiment" type="string"/>
    </complexType>
    <element name="locus" type="locus:locus"/>
</schema>

=== HOSTbioinformatics/ExchangeFormats/XML-Formats/examples/locusESC.xml
<?xml version="1.0" encoding="UTF-8"?>
<locus experiment="experiment" chromosome="chr14" firstbase="47589054"
       lastbase="47593031"
       xmlns="http://bioinformatics.hochschule-stralsund.de/locus"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:schemaLocation="http://bioinformatics.hochschule-stralsund.de/locus ../locus.xsd">
    <nucleosome>
        <pos>47589066</pos>
        <mpos>47589213</mpos>
    </nucleosome>
    <nucleosome>
        <pos>47589300</pos>
        <mpos>47589447</mpos>
    </nucleosome>
    <nucleosome>
        <pos>47589480</pos>
        <mpos>47589627</mpos>
    </nucleosome>
    <nucleosome>
        <pos>47589628</pos>
        <mpos>47589775</mpos>
    </nucleosome>
    <nucleosome>
        <pos>47589776</pos>
        <mpos>47589923</mpos>
    </nucleosome>
    <nucleosome>
        <pos>47589950</pos>
        <mpos>47590097</mpos>
    </nucleosome>
    <nucleosome>
        <pos>47590176</pos>
        <mpos>47590323</mpos>
    </nucleosome>
    <nucleosome>
        <pos>47590324</pos>
        <mpos>47590471</mpos>
    </nucleosome>
    <nucleosome>
        <pos>47590472</pos>
        <mpos>47590619</mpos>
    </nucleosome>
    <nucleosome>
        <pos>47590620</pos>
        <mpos>47590767</mpos>
    </nucleosome>
    <nucleosome>
        <pos>47590822</pos>
        <mpos>47590969</mpos>
    </nucleosome>
    <nucleosome>
        <pos>47590976</pos>
        <mpos>47591123</mpos>
    </nucleosome>
    <nucleosome>
        <pos>47591204</pos>
        <mpos>47591351</mpos>
    </nucleosome>
    <nucleosome>
        <pos>47591352</pos>
        <mpos>47591499</mpos>
    </nucleosome>
    <nucleosome>
        <pos>47591518</pos>
        <mpos>47591665</mpos>
    </nucleosome>
    <nucleosome>
        <pos>47591745</pos>
        <mpos>47591892</mpos>
    </nucleosome>
    <nucleosome>
        <pos>47591913</pos>
        <mpos>47592060</mpos>
    </nucleosome>
    <nucleosome>
        <pos>47592061</pos>
        <mpos>47592208</mpos>
    </nucleosome>
    <nucleosome>
        <pos>47592209</pos>
        <mpos>47592356</mpos>
    </nucleosome>
    <nucleosome>
        <pos>47592414</pos>
        <mpos>47592561</mpos>
    </nucleosome>
    <nucleosome>
        <pos>47592562</pos>
        <mpos>47592709</mpos>
    </nucleosome>
    <nucleosome>
        <pos>47592884</pos>
        <mpos>47593031</mpos>
    </nucleosome>
</locus>
