=== HOSTbioinformatics/ExchangeFormats/XML-Formats/definitions/trajectory.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema targetNamespace="http://bioinformatics.hochschule-stralsund.de/trajectory" 
elementFormDefault="qualified" xmlns="http://www.w3.org/2001/XMLSchema" 
xmlns:trj="http://bioinformatics.hochschule-stralsund.de/trajectory">
    <simpleType name="type_angle">
        <restriction base="double">
            <minInclusive value="-360.0"/>
            <maxInclusive value="360.0"/>
        </restriction>
    </simpleType>
    <simpleType name="type_gt_zero_double">
        <restriction base="double">
            <minExclusive value="0"/>
        </restriction>
    </simpleType>
    <complexType name="Vector3D">
        <sequence>
            <element name="x" type="double" maxOccurs="1" minOccurs="1"/>
            <element name="y" type="double" maxOccurs="1" minOccurs="1"/>
            <element name="z" type="double" maxOccurs="1" minOccurs="1"/>
        </sequence>
    </complexType>
    <complexType name="Bead" abstract="true">
        <sequence>
            <element name="id" type="unsignedInt" maxOccurs="1" minOccurs="1"/>
            <element name="equilibrium_segment_length" maxOccurs="1" minOccurs="1" type="trj:type_gt_zero_double"/>
            <element name="intrinsic_twist" type="trj:type_angle" maxOccurs="1" minOccurs="1"/>
            <element name="position" type="trj:Vector3D" maxOccurs="1" minOccurs="1"/>
            <element name="f_vector" type="trj:Vector3D" maxOccurs="1" minOccurs="1"/>
            <element name="bend_vector" type="trj:Vector3D" maxOccurs="1" minOccurs="1"/>
            <element name="segment_vector" type="trj:Vector3D" maxOccurs="1" minOccurs="1"/>
        </sequence>
    </complexType>
    <complexType name="DNABead">
        <complexContent>
            <extension base="trj:Bead">
                <sequence>
                    <element name="charged" type="boolean" maxOccurs="1" minOccurs="1"/>
                </sequence>
            </extension>
        </complexContent>
    </complexType>
    <complexType name="NucleosomeBead">
        <complexContent>
            <extension base="trj:Bead">
                <sequence>
                    <element name="center_orientation_vector" type="trj:Vector3D" maxOccurs="1" minOccurs="1"/>
                    <element name="center" type="trj:Vector3D" maxOccurs="1" minOccurs="1"/>
                </sequence>
            </extension>
        </complexContent>
    </complexType>
    <complexType name="BeadList">
        <choice maxOccurs="unbounded" minOccurs="0">
            <element name="dnabead" type="trj:DNABead"/>
            <element name="nucleosomebead" type="trj:NucleosomeBead"/>
        </choice>
    </complexType>
    <complexType name="Parameter">
        <sequence>
            <element name="name" type="string" maxOccurs="1" minOccurs="1"/>
            <element name="value" type="string" maxOccurs="1" minOccurs="1"/>
        </sequence>
    </complexType>
    <complexType name="ParameterList">
        <sequence>
            <element name="parameter" type="trj:Parameter" maxOccurs="unbounded" minOccurs="0"/>
        </sequence>
    </complexType>
    <complexType name="Configuration">
        <sequence>
            <element name="mc_steps" type="unsignedInt" maxOccurs="1" minOccurs="1"/>
            <element name="overwrite_parameters" type="trj:ParameterList" maxOccurs="1" minOccurs="0"/>
            <element name="beads" type="trj:BeadList" maxOccurs="1" minOccurs="1"/>
        </sequence>
    </complexType>
    <complexType name="ConfigurationList">
        <sequence>
            <element name="configuration" type="trj:Configuration" maxOccurs="unbounded" minOccurs="1"/>
        </sequence>
    </complexType>
    <complexType name="Trajectory">
        <sequence>
            <element name="date" type="string" maxOccurs="1" minOccurs="1"/>
            <element name="schema_version" type="string" maxOccurs="1" minOccurs="1"/>
            <element name="program" type="string" maxOccurs="1" minOccurs="1"/>
            <element name="program_version" type="string" maxOccurs="1" minOccurs="1"/>
            <element name="parameters" type="trj:ParameterList" maxOccurs="1" minOccurs="1"/>
            <element name="configurations" type="trj:ConfigurationList" maxOccurs="1" minOccurs="1"/>
        </sequence>
    </complexType>
    <element name="trajectory" type="trj:Trajectory"/>
</schema>

=== HOSTbioinformatics/ExchangeFormats/XML-Formats/examples/exampleExchangeTrajectory.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<trajectory xmlns="http://bioinformatics.fh-stralsund.de/trajectory" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://bioinformatics.fh-stralsund.de/trajectory trajectory.xsd">

  <date>Mon Feb 18 00:09:19 2019</date>

  <schema_version>1.0</schema_version>

  <program>BlockTrj2XmlTrjConverter</program>

  <program_version>svnXXXX</program_version>

  <parameters>
    <parameter>
      <name>NumberOfBeads</name>
      <value>8</value>
    </parameter>
    <parameter>
      <name>Temperature</name>
      <value>293</value>
    </parameter>
    <parameter>
      <name>EStatTemperature</name>
      <value>293</value>
    </parameter>
    <parameter>
      <name>EnergyBend</name>
      <value>1</value>
    </parameter>
    <parameter>
      <name>EnergyEstat</name>
      <value>1</value>
    </parameter>
    <parameter>
      <name>EnergyLJ</name>
      <value>1</value>
    </parameter>
    <parameter>
      <name>EnergyStretch</name>
      <value>1</value>
    </parameter>
    <parameter>
      <name>EnergyTorsion</name>
      <value>1</value>
    </parameter>
    <parameter>
      <name>EnergyPulling</name>
      <value>0</value>
    </parameter>
    <parameter>
      <name>EnergySurface</name>
      <value>0</value>
    </parameter>
    <parameter>
      <name>EnergyDNANucColl</name>
      <value>1</value>
    </parameter>
    <parameter>
      <name>RadiusDNA</name>
      <value>1.2</value>
    </parameter>
    <parameter>
      <name>NucleosomeRadius</name>
      <value>5.5</value>
    </parameter>
    <parameter>
      <name>ChainIsClosed</name>
      <value>0</value>
    </parameter>
    <parameter>
      <name>AlphaSDNA</name>
      <value>665</value>
    </parameter>
    <parameter>
      <name>AlphaSNuc</name>
      <value>665</value>
    </parameter>
    <parameter>
      <name>AlphaBDNA</name>
      <value>120.44</value>
    </parameter>
    <parameter>
      <name>AlphaBNuc</name>
      <value>120.44</value>
    </parameter>
    <parameter>
      <name>AlphaTDNA</name>
      <value>156.57</value>
    </parameter>
    <parameter>
      <name>AlphaTNuc</name>
      <value>782.85</value>
    </parameter>
    <parameter>
      <name>LJNucType</name>
      <value>2</value>
    </parameter>
    <parameter>
      <name>SigmaLJNuc</name>
      <value>10.3</value>
    </parameter>
    <parameter>
      <name>EpsLJNuc</name>
      <value>0.65</value>
    </parameter>
    <parameter>
      <name>ChiNucLJ</name>
      <value>0</value>
    </parameter>
    <parameter>
      <name>ChiBarNucLJ</name>
      <value>0</value>
    </parameter>
    <parameter>
      <name>IonicStrength</name>
      <value>0.1</value>
    </parameter>
    <parameter>
      <name>ChargeReductionFactor</name>
      <value>0.5</value>
    </parameter>
    <parameter>
      <name>ComputeEstatAtNucleosome</name>
      <value>0</value>
    </parameter>
    <parameter>
      <name>PhiMaxMCBeadR</name>
      <value>0.025</value>
    </parameter>
    <parameter>
      <name>EveryNthMCBeadR</name>
      <value>4</value>
    </parameter>
    <parameter>
      <name>ShiftMaxMCBeadShift</name>
      <value>0.1</value>
    </parameter>
    <parameter>
      <name>PhiMaxFVecMCShift</name>
      <value>0.02</value>
    </parameter>
    <parameter>
      <name>ThetaMaxMCBranched</name>
      <value>0.02</value>
    </parameter>
    <parameter>
      <name>PhiMaxFVecMC</name>
      <value>0.02</value>
    </parameter>
    <parameter>
      <name>PhiMaxMCPivot</name>
      <value>0.35</value>
    </parameter>
    <parameter>
      <name>EstatType</name>
      <value>2</value>
    </parameter>
    <parameter>
      <name>CutoffEstat</name>
      <value>18.6</value>
    </parameter>
    <parameter>
      <name>CutoffMinDistEstat</name>
      <value>0.1303</value>
    </parameter>
    <parameter>
      <name>DNANucIntersectionNucType</name>
      <value>1</value>
    </parameter>
    <parameter>
      <name>CutoffLJNuc</name>
      <value>3.5</value>
    </parameter>
    <parameter>
      <name>CutoffNucDNAColl</name>
      <value>15.375</value>
    </parameter>
  </parameters>

  <configurations>
    <configuration>
      <mc_steps>0</mc_steps>
      <overwrite_parameters/>
      <beads>
        <dnabead>
          <id>0</id>
          <equilibrium_segment_length>6.8</equilibrium_segment_length>
          <intrinsic_twist>0</intrinsic_twist>
          <position>
            <x>0</x>
            <y>0</y>
            <z>0</z>
          </position>
          <f_vector>
            <x>0</x>
            <y>0</y>
            <z>1</z>
          </f_vector>
          <bend_vector>
            <x>1</x>
            <y>0</y>
            <z>0</z>
          </bend_vector>
          <segment_vector>
            <x>6.8</x>
            <y>0</y>
            <z>0</z>
          </segment_vector>
          <charged>true</charged>
        </dnabead>
        <dnabead>
          <id>1</id>
          <equilibrium_segment_length>6.8</equilibrium_segment_length>
          <intrinsic_twist>-0.43633231</intrinsic_twist>
          <position>
            <x>6.8</x>
            <y>0</y>
            <z>0</z>
          </position>
          <f_vector>
            <x>0</x>
            <y>0</y>
            <z>1</z>
          </f_vector>
          <bend_vector>
            <x>-0</x>
            <y>1</y>
            <z>0</z>
          </bend_vector>
          <segment_vector>
            <x>6.8</x>
            <y>0</y>
            <z>0</z>
          </segment_vector>
          <charged>true</charged>
        </dnabead>
        <nucleosomebead>
          <id>2</id>
          <equilibrium_segment_length>8</equilibrium_segment_length>
          <intrinsic_twist>-4.13643033</intrinsic_twist>
          <position>
            <x>13.6</x>
            <y>0</y>
            <z>0</z>
          </position>
          <f_vector>
            <x>0</x>
            <y>0</y>
            <z>1</z>
          </f_vector>
          <bend_vector>
            <x>-0</x>
            <y>0.90630779</y>
            <z>-0.42261826</z>
          </bend_vector>
          <segment_vector>
            <x>8</x>
            <y>0</y>
            <z>0</z>
          </segment_vector>
          <center_orientation_vector>
            <x>0.98480775</x>
            <y>0.17364818</y>
            <z>0</z>
          </center_orientation_vector>
          <center>
            <x>18.16433324</x>
            <y>-0.97745384</y>
            <z>3.10098565</z>
          </center>
        </nucleosomebead>
        <dnabead>
          <id>3</id>
          <equilibrium_segment_length>6.46</equilibrium_segment_length>
          <intrinsic_twist>0</intrinsic_twist>
          <position>
            <x>21.6</x>
            <y>0</y>
            <z>0</z>
          </position>
          <f_vector>
            <x>0</x>
            <y>-0</y>
            <z>-1</z>
          </f_vector>
          <bend_vector>
            <x>1</x>
            <y>0</y>
            <z>0</z>
          </bend_vector>
          <segment_vector>
            <x>6.46</x>
            <y>0</y>
            <z>0</z>
          </segment_vector>
          <charged>true</charged>
        </dnabead>
        <dnabead>
          <id>4</id>
          <equilibrium_segment_length>6.46</equilibrium_segment_length>
          <intrinsic_twist>-0.43633231</intrinsic_twist>
          <position>
            <x>28.06</x>
            <y>0</y>
            <z>0</z>
          </position>
          <f_vector>
            <x>0</x>
            <y>-0</y>
            <z>-1</z>
          </f_vector>
          <bend_vector>
            <x>-0</x>
            <y>-1</y>
            <z>0</z>
          </bend_vector>
          <segment_vector>
            <x>6.46</x>
            <y>0</y>
            <z>0</z>
          </segment_vector>
          <charged>true</charged>
        </dnabead>
        <nucleosomebead>
          <id>5</id>
          <equilibrium_segment_length>8</equilibrium_segment_length>
          <intrinsic_twist>-2.25147474</intrinsic_twist>
          <position>
            <x>34.52</x>
            <y>0</y>
            <z>0</z>
          </position>
          <f_vector>
            <x>0</x>
            <y>-0</y>
            <z>-1</z>
          </f_vector>
          <bend_vector>
            <x>-0</x>
            <y>-0.90630779</y>
            <z>0.42261826</z>
          </bend_vector>
          <segment_vector>
            <x>8</x>
            <y>0</y>
            <z>0</z>
          </segment_vector>
          <center_orientation_vector>
            <x>0.98480775</x>
            <y>-0.17364818</y>
            <z>0</z>
          </center_orientation_vector>
          <center>
            <x>39.08433324</x>
            <y>0.97745384</y>
            <z>-3.10098565</z>
          </center>
        </nucleosomebead>
        <dnabead>
          <id>6</id>
          <equilibrium_segment_length>5.1</equilibrium_segment_length>
          <intrinsic_twist>0</intrinsic_twist>
          <position>
            <x>42.52</x>
            <y>0</y>
            <z>0</z>
          </position>
          <f_vector>
            <x>0</x>
            <y>0</y>
            <z>1</z>
          </f_vector>
          <bend_vector>
            <x>1</x>
            <y>0</y>
            <z>0</z>
          </bend_vector>
          <segment_vector>
            <x>5.1</x>
            <y>0</y>
            <z>0</z>
          </segment_vector>
          <charged>true</charged>
        </dnabead>
        <dnabead>
          <id>7</id>
          <equilibrium_segment_length>5.1</equilibrium_segment_length>
          <intrinsic_twist>0</intrinsic_twist>
          <position>
            <x>47.62</x>
            <y>0</y>
            <z>0</z>
          </position>
          <f_vector>
            <x>0</x>
            <y>0</y>
            <z>1</z>
          </f_vector>
          <bend_vector>
            <x>1</x>
            <y>0</y>
            <z>0</z>
